name: flutter_tutorial_final
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0

  #Use to projects_screen 02 Infinite List
  meta: ^1.3.0
  provider: ^6.0.2

  #Use to projects_screen 03 Linting Tool
  adaptive_breakpoints: ^0.1.1
  equatable: ^2.0.3
  file_selector: ^0.9.1
  flutter_markdown: ^0.6.2
  google_fonts: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  json2yaml: ^3.0.0
  json_annotation: ^4.5.0
  mockito: ^5.0.13
  yaml: ^3.1.0
  context_menus: ^1.0.1

  #Use to projects_screen 04 Isolate App
  #provider: ^6.0.2

  #Use to projects_screen 05 Bookstore App
  adaptive_navigation: ^0.0.3
  collection: ^1.15.0
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  url_strategy: ^0.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  #Use to projects_screen 03 Linting Tool
  build_runner: ^2.0.6
  hive_generator: ^2.0.0
  json_serializable: ^6.2.0


  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size



flutter:
  uses-material-design: true
  assets:
   - assets/
   - images/
   - images/characters/
   - images/balls/
   - images/shoes/
   - images/credit_cards/
   - assets/